ALTER TABLE camp_wellness ADD COLUMN appetite INTEGER NOT NULL DEFAULT 0;
ALTER TABLE camp_wellness ADD COLUMN desire   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE camp_wellness ADD COLUMN duration INTEGER NOT NULL DEFAULT 0;
